spring.application.name=backend

# Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/medistock_db
spring.datasource.username=postgres
spring.datasource.password=sanjana20
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Server Port
server.port=8080

jwt.secret=medistock_secret_key_2024_very_long_secret_key
jwt.expiration=86400000
spring.security.enabled=false