spring.application.name=backend

# Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/medistock_db
spring.datasource.username=postgres
spring.datasource.password=sanjana20
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Server Port
server.port=8080

jwt.secret=medistock_secret_key_2024_very_long_secret_key
jwt.expiration=86400000
spring.security.enabled=false

# Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=bec.leavems2025@gmail.com
spring.mail.password=fmtcdjlygqjxljxv
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# Admin email to receive alerts
app.admin.email=bec.leavems2025@gmail.com